config/routes.rb
Rails.application.routes.draw do
  root :to => "sessions#create"
  get 'login' => "sessions#create" , as: 'login'
  get 'callback' => "sessions#callback" , as: 'callback'
  get 'load_user' => "sessions#load_user", :as => 'load_user'
  get 'logout' => "sessions#destroy", :as => 'logout'
 
  resources :accounts do
    resources :transactions
  end

  resources :payments do
    member do 
      get 'mtan'
      get 'deny'
      get 'approve'
      patch 'mtan_confirm'
    end
    collection do
      get 'to_approve'
      get 'for_approval'
    end
  end
 
  get '*path' => "four_o_four#index" , as: 'pagenotfound'
  

end

app/models/payment.rb
class Payment < ActiveRecord::Base

validates_presence_of :account_id , :transaction_number , :amount , :currency , :iban , :bic , :status_id, :uuid
belongs_to :account
belongs_to :status
after_initialize :init

  def init
    self.transaction_number  ||= "-"
    self.currency ||= "euro"  #TODO load from DB
  end
  
  def pretty_created_at
    self.created_at.strftime("%FT%T") 
  end

  def can_approve?(user_id)
    return (user_id == self.account.approver_id)? true : false
  end

  def is_denied?
  	return (self.status.name == Constants::PAYMENT_2MC_DENIED_STATUS)? true : false
  end

  def is_modified?
    return (self.status.name == Constants::PAYMENT_MODIFIED_STATUS)? true : false
  end

  def can_complete?
   
    if (self.status.name == Constants::PAYMENT_MODIFIED_STATUS || self.status.name == Constants::PAYMENT_CREATED_STATUS)
      self.status = Status.where(:name=>Constants::PAYMENT_MTANCONFIRMED_STATUS).first
      return true unless self.account.is_tmr?
    end

    if (self.status.name == Constants::PAYMENT_2MC_CHECKED_STATUS)
      self.status = Status.where(:name=>Constants::PAYMENT_2MC_MTANCONFIRMED_STATUS).first 
      return true
    end

    return false
  
  end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_filter :authenticate_user
  before_filter :payment_permissions?
  around_filter :oauth_exception, only:[:create, :mtan_confirm, :mtan, :update]
  before_action :set_payment, only: [:show, :edit, :update, :destroy]
  before_action :load_oauth
  layout "mtan", only: [:mtan]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.joins(:account,:status).where(accounts: {customer_id:session[:id]}).
                  page(params[:page])
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
	  @payment = Payment.find(params[:id])
  end

  # GET /payments/new
  def new
    @accounts = Account.where(:customer_id=> session[:id])
    @payment = Payment.new
    status  = Status.where(:name=>Constants::PAYMENT_CREATED_STATUS).first
    @payment.status = status
  end

  # GET /payments/1/edit
  def edit
    @accounts = Account.where(:customer_id=> session[:id])
    @payment = Payment.find(params[:id])
    status  = Status.where(:name=>Constants::PAYMENT_MODIFIED_STATUS).first
    @payment.status = status
  end

  # POST /payments
  # POST /payments.json
  def create
    @account = Account.find(payment_params[:account_id])
    @account_detail = @client.get_account_detail(@account.account_fidor_id)
    @payment = Payment.new(payment_params)
    if @account_detail.can_transfer?(payment_params['amount'])
      @payment.account = @account
      status  = Status.where(:name=>Constants::PAYMENT_CREATED_STATUS).first
      @payment.status = status
      @payment.uuid = SecureRandom.uuid
      respond_to do |format|
        if @payment.save
          format.html { redirect_to mtan_payment_path(@payment) }
        else
          format.html { render :new }
        end
      end  
    else
      @payment.errors.add(:base, " Amount unavailable ")
      respond_to do |format|
        format.html { render :new }
      end
    end

  end
  
  
  def mtan 
	  @payment = Payment.find(params[:id])
    @client.request_mtan(@payment)
  end
  
  def mtan_confirm

    @payment = Payment.find(params[:id])
    @account_detail = @client.get_account_detail(@payment.account.account_fidor_id)
    if @account_detail.can_transfer?(@payment.amount)
      if @client.mtan_valid?(params[:mtan])
        if @payment.can_complete?
          id = @client.post_payment(@payment)
          @payment.transaction_number = id
          status  = Status.where(:name=>Constants::PAYMENT_COMPLETED_STATUS).first
          #obtengo el id de la transaccion
          flash[:notice] = 'This Payment has been procesed ' #todo to locale
        else
          status  = Status.where(:name=>Constants::PAYMENT_2MC_CHECKED_STATUS).first
          flash[:notice] = 'This Payment its configured by TMR and must be Approved ' #todo to locale
        end
        @payment.status = status
        @payment.save
        redirect_to :payment
      else
        flash[:notice] = 'Invalid MTAN ' #todo to locale
        redirect_to mtan_account_payment_path(@account,@payment)
      end
    else
      flash[:notice] = 'Amount unavailable ' #todo to locale
      redirect_to edit_account_payment_path(@account,@payment)
    end

  end

  def to_approve  # lista de payments pendientes de mi aprobacion
    @payments = Payment.joins(:account,:status).where(accounts: {approver_id:session[:id]}).
                  where(statuses:{ name: "2mc_checked"}).page(params[:page])
    render "index"
  end

  def for_approval # lista de payments pendientes de aprobacion de otros
    @payments = Payment.joins(:account,:status).where(accounts: {two_man_rule:true}).
                  where.not(accounts: {approver_id:session[:id]}).
                  where(statuses:{ name: "2mc_checked"}).page(params[:page])
    render "index"
  end

  def deny
    @accounts = Account.where(:customer_id=> session[:id])
    @payment = Payment.find(params[:id])
    status = Status.where(:name=>Constants::PAYMENT_2MC_DENIED_STATUS).first
    @payment.status = status
    render "edit"
  end

  def approve
    @payment = Payment.find(params[:id])
    redirect_to mtan_payment_path(@payment)
  end


  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update

	  @payment = Payment.find(params[:id])
    status = Status.find(payment_params[:status_id])
    @payment.status = status
    @account = Account.find(payment_params[:account_id])
    if @payment.is_denied?
      respond_to do |format|
        if @payment.update(payment_params)
          format.html { redirect_to payments_path }
        else
          format.html { render :edit }
        end
      end
    else
      @account_detail = @client.get_account_detail(@account.account_fidor_id)
      if @account_detail.can_transfer?(payment_params['amount'])
        respond_to do |format|
          if @payment.update(payment_params)
            format.html { redirect_to mtan_payment_path(@payment) }
          else
            format.html { render :edit }
          end
        end
      else
        @payment.errors.add(:base, " Amount unavailable ")
        respond_to do |format|
          format.html { render :edit }
        end
      end
    end

  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
     params.require(:payment).permit(:account_id, :iban, :bic, :status_id, 
              :amount,:txt_reference,:name,:txt_rejected_reference)
    end
	
	
  def oauth_exception
    begin
      yield
    rescue ActiveRecord::RecordNotFound => error
      flash[:error] = error.instance_values
      respond_with @account_detail
    rescue Exceptions::OAuthConnError, Exceptions::OAuthHTTPStatusError => error
      flash[:error] = error.instance_values
      respond_with @account_detail
    rescue Exceptions::OAuthProcessStatusError => error
      redirect_to logout_url, :notice => error.message
    end
  end
  
end

app/helpers/payments_helper.rb
module PaymentsHelper


 
end

app/views/payments/_form.html.erb
<%= form_for (@payment),:html=>{:class =>'form-horizontal'} do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation" class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <h4><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h4>
      <ul>
        <% @payment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if flash[:notice] %>
    <div id="error_explanation" class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <h4><%= flash[:notice] %></h4>
    </div>
  <% end %>

  <%= f.hidden_field :status_id, value:@payment.status.id %>

  <% if @payment.status.is_denied? %>
    <div class="control-group">
      <%= f.label "Account:", class: "control-label" %>
      <div class="controls">
        <%= f.text_field "account_number", class: "span5",value:@payment.account.account_number, disabled:true %>
        <%= f.hidden_field :account_id, value:@payment.account.id %>
      </div>
    </div>
  <% else %>
    <div class="control-group">
      <%= f.label "Account:", class: "control-label" %>
      <div class="controls">
        <%= f.select :account_id, options_from_collection_for_select(@accounts, "id", "account_number") %>
      </div>
    </div>
  <% end %>


  <div class="control-group">
	<%= f.label :iban,"Remote IBAN:", class: "control-label" %>
    <div class="controls">
	  <%= f.text_field :iban,required: true, maxlength: 34, class: "span5",disabled:@payment.status.is_denied? %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :name,"Remote Name:", class: "control-label" %>
    <div class="controls">
      <%= f.text_field :name, required: true, maxlength: 70, class: "span5",disabled:@payment.status.is_denied? %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :bic,"Remote BIC:", class: "control-label" %>
    <div class="controls">
      <%= f.text_field :bic, required: true,maxlength: 11, class: "span5",disabled:@payment.status.is_denied? %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :amount,"Amount:", class: "control-label" %>
    <div class="controls">
      <%= f.text_field :amount, required: true,maxlength: 7, class: "span2",disabled:@payment.status.is_denied? %>
    </div>
  </div>

  <% if @payment.is_denied? %>
    <div class="control-group">
      <label class="control-label" for="inputref">Reject Reference:</label>
      <div class="controls">
	      <%= f.text_area :txt_rejected_reference, {required: true, class: "span5",rows: 5} %>
      </div>
    </div>
  <% else %>
    <div class="control-group">
      <label class="control-label" for="inputref">Reference:</label>
      <div class="controls">
        <%= f.text_area :txt_reference, {required: true, class: "span5",rows: 5} %>
      </div>
    </div>
  <% end %>
  
  <div class="control-group">
    <div class="controls">
	  <%= f.submit ( f.object.new_record? ? "Create Payment" : "Update Payment"),{class: "btn btn-default span2"} %>
	</div>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<div class="page-header">
  <h1>Listing Available payments <small>for this account</small></h1>
</div>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>ID</th>
	  <th>Account Number</th>
    <th>Amount</th>
    <th>Remote Iban</th>
    <th>Remote BIC</th>
    <th>Created at</th>
	  <th>Status</th>
	  <th>Action</th>
    </tr>
  </thead>

  <tbody>
  <% @payments.each do |payment| %>
    <tr> 
	    <td><%= payment.id %></td>
		  <td><%= payment.account.account_number %></td>
      <td><%= payment.amount %></td>
      <td><%= payment.iban %></td>
      <td><%= payment.bic %></td>
      <td><%= payment.pretty_created_at %></td>
		  <td><%= payment.status.name %></td>
    <% if payment.can_approve?(session[:id]) %>
      <td>
        <%= link_to 'Approve',approve_payment_path(payment) %> /
        <%= link_to 'Deny', deny_payment_path(payment) %>
      </td>
    <% else %>
      <td>
        <% if payment.is_denied? %>
          <%= link_to 'Delete',payment_path(payment), method: :delete, data: { confirm: 'Are you certain you want to delete this?' } %> /
          <%= link_to 'Modify', edit_payment_path(payment) %>
        <% else %>
          <%= link_to 'Show',[@account,payment] %>
        <% end %>
      </td>
     <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
  <%= paginate @payments %>
  <%= page_entries_info @payments %> 
<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/mtan.html.erb
<%= form_for (@payment),:url => mtan_confirm_payment_path, :html=>{:class =>'form-vertical'} do |f| %>
  <legend><%= t('views.payments.show.page_mtan_title') %></legend>
  <% if flash[:notice] %>
    <div id="error_explanation" class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <h4><%= flash[:notice] %></h4>
    </div>
  <% end %>
  <p><%= t('views.payments.show.page_mtan_teaser') %></p>
  <div class="control-group">
    <label class="control-label" for="name">mTan</label>
    <div class="controls">
      <input type="text" id="name" name="mtan" />
    </div>
  </div>
  <div class="form-actions rimless">
    <input class="btn btn-green" type="submit" value="<%= t('views.payments.show.page_mtan_button') %>" />
  </div>
<% end %>

app/views/payments/new.html.erb
<div class="page-header">
  <h1><%= t('views.payments.show.page_listing_payments_title')%> <small>Subtext for header</small></h1>
</div>
<div class="well well-box">
  <h5>Payment Details</h5>
  <%= render 'form' %>
</div>
<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<%= div_for @payment do %>
<h4>Amount:<%= @payment.amount %></h4>
<h4>Account Number:<%= @payment.account.account_number %></h4>
<% end %>

<h4> Mostrar el ID de Transacci&oacute;n</h4>
<%= link_to 'Edit', edit_payment_path %> |
<%= link_to 'Back', payments_path %>