config/routes.rb
Rails.application.routes.draw do
  root :to => "sessions#create"
  get 'login' => "sessions#create" , as: 'login'
  get 'callback' => "sessions#callback" , as: 'callback'
  get 'load_user' => "sessions#load_user", :as => 'load_user'
  get 'logout' => "sessions#destroy", :as => 'logout'
 
  resources :accounts do
    resources :transactions
  end

  resources :payments do
    member do 
      get 'mtan'
      get 'deny'
      get 'approve'
      patch 'mtan_confirm'
    end
    collection do
      get 'to_approve'
      get 'for_approval'
    end
  end
 
  get '*path' => "four_o_four#index" , as: 'pagenotfound'
  

end

app/views/layouts/_footer.html.erb
    </div>
  </div>
</div>
<div id="footer">
 <div id="links-footer-shadow"><!--//--></div>
 <div id="links-footer-wrapper">
    <div id="links-footer" class="row">
      <div class="span4 links-footer-block">
        <h3>Headline 1</h3>
        <ul class="links-footer-contact">
          <li><span>Fax:</span><a href="#">(089) 123 45 678</a></li>
        </ul>
        <ul class="links-footer-info">
          <li class="links-footer-info-email"><a href="#">Contact via E-Mail</a></li>
          <li><a href="#">Random PDF Document</a></li>
          <li><a href="#">FAQ Link</a></li>
          <li><a href="#">Random Newsletter Link</a></li>
        </ul>
      </div>
      <div class="span4 links-footer-block">
        <h3>Headline 2</h3>
        <ul class="links-footer-contact">
          <li><span>Fax:</span><a href="#">(089) 123 45 678</a></li>
        </ul>
        <ul class="links-footer-info">
          <li class="links-footer-info-email"><a href="#">Contact via E-Mail</a></li>
          <li><a href="#">Random PDF Document</a></li>
          <li><a href="#">FAQ Link</a></li>
          <li><a href="#">Random Newsletter Link</a></li>
        </ul>
      </div>
      <div class="span4">
        <h3>Fidor & Social Media</h3>
        <div class="clearfix">
          <ul class="social-media">
            <li class="facebook-square"><a href="http://www.facebook.com/fidorbank" title="Fidor Bank Facebook-Seite">Facebook</a></li>
            <li class="twitter-square"><a href="http://twitter.com/ficoba" title="Folge der Fidor Bank auf Twitter">Twitter</a></li>
            <li class="youtube-square"><a href="http://www.youtube.com/user/FidorCommBanking" title="Videobeiträge der Fidor Bank auf YouTube">YouTube</a></li>
            <li class="googleplus-square"><a href="https://plus.google.com/108681236199837180740" title="Folge der Fidor Bank auf Google+">Google+</a></li>
            <li class="community-square"><a href="https://community.fidor.de/produktbewertung" title="Bewertungen in der Fidor Bank Community anlegen">Community</a></li>
            <li class="trustpilot-square"><a href="http://www.trustpilot.de/review/www.fidor.de" title="Fidor Bank Bewertung auf TrustPilot">Trustpilot</a></li>
            <li class="ciao-square"><a href="http://www.ciao.de/sr/q-fidor" title="Fidor Bank Erfahrungsberichte auf ciao.de">ciao!</a></li>
            <li class="slideshare-square"><a href="http://de.slideshare.net/ficoba" title="Fidor Bank Präsentationen auf slideshare">slideshare</a></li>

            <li class="facebook-circle"><a href="#" title="">social</a></li>
            <li class="vkontakte-circle"><a href="#" title="">social</a></li>
            <li class="twitter-circle"><a href="#" title="">social</a></li>
            <li class="youtube-circle"><a href="#" title="">social</a></li>
            <li class="odnoklassniki-circle"><a href="#" title="">social</a></li>
            <li class="google-circle"><a href="#" title="">social</a></li>
            <li class="community-circle"><a href="#" title="">social</a></li>
            <li class="slideshare-circle"><a href="#" title="">social</a></li>
            <li class="blogger-circle"><a href="#" title="">social</a></li>
            <li class="linkedin-circle"><a href="#" title="">social</a></li>
          </ul>
        </div>
        <h3>Fidor Bank Gruppe</h3>
        <a href="http://www.fidor.de" style="text-decoration: none; min-height: 60px;">
          <img alt="Footer-fidor-bank" height="40" src="/public/styleguide/facelift/layouts/facelift/footer-fidor-bank.png" style="margin-bottom: 10px;" width="90">
        </a>
        <a href="http://www.fidortecs.de" style="text-decoration: none;">
          <img alt="Footer-fidor-tecs" height="40" src="/public/styleguide/facelift/layouts/facelift/footer-fidor-tecs.png" style="margin-bottom: 10px;" width="90">
        </a>
        <a href="http://www.fidorpays.de" style="text-decoration: none;">
          <img alt="Footer-fidor-pays" height="40" src="/public/styleguide/facelift/layouts/facelift/footer-fidor-pays.png" style="margin-bottom: 10px;" width="90">
        </a>
      </div>
    </div>
 </div>

 <div id="navigation-footer-wrapper">
    <div class="row">
      <div class="span12">
        <ul id="navigation-footer">
          <li><a href="https://www.fidor.de/impressum">Impressum</a></li>
          <li><a href="https://www.fidor.de/haftung">Haftung</a></li>
          <li><a href="https://www.fidor.de/kontakt">Kontakt</a></li>
          <li><a href="https://www.fidor.de/presse">Presse</a></li>
          <li><a href="https://www.fidor.de/fidor-bank/stellenangebote">Karriere</a></li>
          <li><a href="https://www.fidor.de/service-center">AGB</a></li>
          <li><a href="https://www.fidor.de/affiliate">Affiliate</a></li>
          <li class="social facebook"><a href="http://www.facebook.com/fidorbank" title="Fidor Bank Facebook-Seite">Facebook</a></li>
          <li class="social twitter"><a href="http://twitter.com/ficoba" title="Folge der Fidor Bank auf Twitter">Twitter</a></li>
          <li class="social youtube"><a href="http://www.youtube.com/user/FidorCommBanking" title="Videobeiträge der Fidor Bank auf YouTube">YouTube</a></li>
          <li class="ie6-last-child"><span>© 2014 <a href="//www.fidor.de/">Fidor Bank AG</a> Alle Rechte vorbehalten.</span></li>
        </ul>
      </div>
    </div>
 </div>
</div>

app/views/layouts/_header.html.erb
<div id="header">
    <div class="row" id="header-navigation">
      <div class="span12">
        <div class="navbar navbar-inverse">
          <div class="navbar-inner">
            <div class="container">
              <div class="nav-collapse">
                <ul class="nav">
                  <li class="dropdown" data-dropdown="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      1st Global App <b class="caret"><!--//--></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><a href="#">Item</a></li>
                      <li><a href="#">Item</a></li>
                    </ul>
                  </li>
                  <li class="dropdown" data-dropdown="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      2nd Global App <b class="caret"><!--//--></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><a href="#">Item</a></li>
                      <li><a href="#">Item</a></li>
                    </ul>
                  </li>
                  <li class="dropdown" data-dropdown="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      3rd Global App <b class="caret"><!--//--></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><a href="#">Item</a></li>
                      <li><a href="#">Item</a></li>
                    </ul>
                  </li>
                </ul>
                <ul class="nav pull-right">
                  <li class="dropdown" data-dropdown="dropdown" id="myaccount-dropdown">
                    <a href="#" class="dropdown-toggle display-inline avatar-holder" data-toggle="dropdown">
                      <img alt="" class="img-circle" src="http://placehold.it/30x30"> <%= session[:email] %>
                    </a>
                    <ul class="dropdown-menu">
                      <li class="nav-header">
                        <%= session[:email] %><br/>Fidor-ID: <%= session[:id] %>
                      </li>
					            <li>
                        <%= link_to t('views.accounts.name') , accounts_path %>
                      </li>
                      <li>
                        <%= link_to "Payments", payments_path if session[:access_right] == "write"%>  
                      </li>
                      <li class="divider"></li>
                      <li><%= link_to t('views.session.logout.name') , logout_path %></li>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="span5">
        <h1>
          <a href="/" accesskey="1">
            <strong>Company Name</strong>
          </a>
        </h1>
      </div>
      <div class="span7">
        <ul id="navigation-service">
          <li><span>  <%= session[:token]  %> </span></li>
          <li><%= language_selector %></li>
          <li><a href="#">Item</a></li>
          <li><a href="#">Item</a></li>
        </ul>
      </div>
    </div>

    <ul id="navigation-social-media">
      <li class="facebook"><a href="http://www.facebook.com/fidorbank" title="Fidor Bank Facebook-Seite">Facebook</a></li>
      <li class="twitter"><a href="http://twitter.com/ficoba" title="Folge der Fidor Bank auf Twitter">Twitter</a></li>
      <li class="youtube"><a href="http://www.youtube.com/user/FidorCommBanking" title="Videobeiträge der Fidor Bank auf YouTube">YouTube</a></li>
      <li class="googleplus"><a href="https://www.fidor.de/+" title="Folge der Fidor Bank auf Google+">Google+</a></li>
    </ul>
 </div>
 <div id="main">
   <div id="section">
     <div id="article" class="container">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CMAT</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> 
<head> 
	<title>CMAT</title>
</head>
<body class="classic">
<div id="wrapper">
<%= render "layouts/header" %> 
<%= yield %>
<%= render "layouts/footer" %>
</div>
</body>
</html>

app/views/layouts/logout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CMAT</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> 
<head> 
	<title>CMAT</title>
</head>
<body class="darkbox boxsp6 vault">
  <div id="wrapper">
    <div id="main">
	  <div id="section">
        <div id="article" class="container">
         <div class="page-header">
           <h1><%= t('views.session.logout.title_header') %></h1>
        </div>
            <%= yield %>
       </div>
      </div>
	</div>
  </div>
  <div id="extra-div">
  </div>
</body>

app/views/layouts/mtan.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CMAT</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> 
<head> 
	<title>CMAT</title>
</head>
<body class="darkbox mtan boxsp6 vault">
  <div id="wrapper">
    <div id="main">
	  <div id="section">
        <div id="article" class="container">
          <%= yield %>
        </div>
	  </div>
	</div>
  </div>
  <div id="extra-div">
  </div>
</body>