config/routes.rb
Rails.application.routes.draw do
  root :to => "sessions#create"
  get 'login' => "sessions#create" , as: 'login'
  get 'callback' => "sessions#callback" , as: 'callback'
  get 'load_user' => "sessions#load_user", :as => 'load_user'
  get 'logout' => "sessions#destroy", :as => 'logout'
 
  resources :accounts do
    resources :transactions
  end

  resources :payments do
    member do 
      get 'mtan'
      get 'deny'
      get 'approve'
      patch 'mtan_confirm'
    end
    collection do
      get 'to_approve'
      get 'for_approval'
    end
  end
 
  get '*path' => "four_o_four#index" , as: 'pagenotfound'
  

end

app/models/account.rb
class Account < ActiveRecord::Base

validates_presence_of :account_number, :account_fidor_id, :two_man_rule, :customer_id, :approver_id ,:is_active
has_many :payments

  def is_tmr?
    return self.two_man_rule 
  end 
  
  
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  
  before_filter :authenticate_user
  before_action :set_account, only: [:show]
  before_action :load_oauth
  around_filter :oauth_exception, only:[:show]
  respond_to :html,:json
 
  def index
    @accounts = Account.where(:customer_id=>session[:id]).page(params[:page])
  end

  def show
    @account_detail = @client.get_account_detail(@account.account_fidor_id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_account
    @account = Account.find(params[:id]) or not_found
  end

  def oauth_exception
	begin
	  yield
	rescue ActiveRecord::RecordNotFound => error
	  flash[:error] = error.instance_values
	  respond_with @account_detail
	rescue Exceptions::OAuthConnError, Exceptions::OAuthHTTPStatusError => error
	  flash[:error] = error.instance_values
	  respond_with @account_detail
	rescue Exceptions::OAuthProcessStatusError => error
	  redirect_to logout_url, :notice => error.message
	end
  end
    
  # Never trust parameters from the scary internet, only allow the white list through.
  def account_params
    params[:account]
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<div class="page-header">
  <h1><%= t('views.accounts.show.page_listing_account_title') %></h1>
</div>
  <% unless @accounts.size ==0 %>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th><%=t('views.accounts.show.page_table_account_number') %></th>
        <th><%=t('views.accounts.show.page_table_account_tmr') %></th>
        <th><%=t('views.accounts.show.page_table_account_active') %></th>
	    <th><%=t('views.accounts.show.page_table_account_operations') %></th>
      </tr>
    </thead>
    <tbody>
      <% @accounts.each do |account|%>
        <tr>
          <td><%= link_to account.account_number, account %></td>
          <td><%= account.two_man_rule %></td>
          <td><%= account.is_active %></td>
          <td>
		   <div class="btn-group">
                <a class="btn dropdown-toggle btn-success" data-toggle="dropdown" href="#"> 
                  <span class="glyphicon icon-cog icon-white"></span><span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
				    <li>
					  <%= link_to "<span class='glyphicon icon-calendar'></span> Transactions".html_safe, account_transactions_path(account)%>  
		    		</li>
					<li>
					  <a href="#" data-toggle="tooltip" title="Get Ebox">
					    <span class="glyphicon icon-list-alt"></span> Statements
					  </a>
					</li>
          </ul>
        </div>
		  </td>
        </tr>
	  <% end %>
    </tbody>
  </table>
  <% end %>
  <%= paginate @accounts %>
  <%= page_entries_info @accounts %> 

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<% if flash[:error] %>
<h1><%= flash[:error] %>   ss</h1>
<% else %>
<div class="page-header">
  <h1><%= t('views.accounts.show.page_listing_account_details_title') %></h1>
</div>
 
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>balance</th>
        <th>balance available</th>
        <th>iban</th>
	    <th>fidor id</th>
		<th>account_number</th>
		<th>two man rule</th>
		<th>active</th>
		<th>local id</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td><%= @account_detail.balance%></td>
          <td><%= @account_detail.balance_available%></td>
          <td><%= @account_detail.iban%></td>
          <td><%= @account_detail.id%></td>
		  <td><%= @account_detail.account_number %></td>
		  <td><%= @account.two_man_rule %></td>
		  <td><%= @account.is_active %></td>
		  <td><%= @account.id %></td>
        </tr>
    </tbody>
  </table>
  <div class="well well-box">
  <h5>Pending Payments</h5>
</div> 

<div class="well well-box">
  <h5>Pending to Payments to be Approved</h5>
</div>
<% end %>
<%= link_to 'Back', accounts_url %>